#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 29 12:29:43 2020

@author: marianne
"""

#!/usr/bin/env python
import os
import glob
import matplotlib.pyplot as plt
import sys
sys.path.insert(1, '../image-segmentation-keras')
from keras_segmentation.data_utils.data_loader import get_image_arr , get_segmentation_arr
from keras_segmentation.predict import predict, model_from_checkpoint_path
from keras_segmentation import metrics
#from keras_segmentation.train import find_latest_checkpoint
import numpy as np
from tqdm import tqdm
import argparse
import time


gt = np.load('gt_array.npy')
pr = np.load('pr_array.npy')
inp = r'Frogn_Dataset/images_prepped_test/frogn_62855.png'
input_image = plt.imread(inp)
iou = metrics.get_iou( gt , pr ,3)
ious = []
ious.append( iou )

#visualization

fig = plt.figure()
plt.title("IOU:"+str(iou))
ax1 = fig.add_subplot(2,2,1)
ax1.imshow(gt-pr)
#ax1.colorbar()
ax1.title.set_text("Difference GT-pred")

ax2 = fig.add_subplot(2,2,2)
ax2.imshow(gt)
ax2.title.set_text('GT')

ax3 = fig.add_subplot(2,2,3)
ax3.imshow(pr)
ax3.title.set_text('pred')

ax4 = fig.add_subplot(2,2,4)
ax4.imshow(input_image)
ax4.title.set_text('Input image')

#make overlay image
image_mask = gt
mask = np.uint8(np.zeros(input_image.shape()))

vis_img = input_image + mask
figure(111)
plt.imshow(vis_img) # fixme downsample input image



