#Base anaconda image to code in conda environtments
#Add base Ubuntu/NVidia image as in tensorflow image
FROM nvidia/cuda:10.0-base-ubuntu18.04

# Anaconda (from Continuum's Anaconda dockerfile): https://hub.docker.com/r/continuumio/anaconda/dockerfile
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda2-5.3.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

CMD [ "/bin/bash" ] 
# Misc
RUN apt-get update && apt-get install -y \
	vim
#AgriNet dependencies
RUN apt-get update && apt-get install -y \
	libgl1-mesa-glx 
# Conda tensorflow-gpu dependencies
RUN conda update -n root conda #need newest conda to specify channel per package

#Create and start agriNet environment
ADD segNet_GPU.yml /tmp/segNet_GPU.yml
RUN conda env create -f /tmp/segNet_GPU.yml
RUN echo "source activate segNet_GPU" > ~/.bashrc
ENV PATH /opt/conda/envs/segNet_GPU/bin:$PATH
