global_frame: /map
robot_base_frame: /base_link

#footprint: [[0.785, 0.60], [0.785, -0.60], [-0.785, -0.60], [-0.785, 0.60]]
#footprint: [[0.67, 0.385], [0.67, -0.385], [-0.67, -0.385], [-0.67, 0.385]]
#footprint: [[0.67, 0.47], [0.67, -0.47], [-0.67, -0.47], [-0.67, 0.47]]
#footprint: [[0.67, 0.65], [0.67, -0.65], [-0.67, -0.65], [-0.67, 0.65]]
footprint: [[0.67, 0.72], [0.67, -0.72], [-0.67, -0.72], [-0.67, 0.72]]

map_layer:
  map_topic: /map

no_go_layer:
  map_topic: /map

global_inflation_layer:
  #inflation_radius: 0.5
  #cost_scaling_factor: 2.0
  inflation_radius: 0.66
  cost_scaling_factor: 0.97

local_inflation_layer:
  #inflation_radius: 0.5
  #cost_scaling_factor: 2.0
  inflation_radius: 0.55 #0.66
  cost_scaling_factor: 1.3 #0.97 

obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0

  track_unknown_space: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

global_obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0

  track_unknown_space: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: false, clearing: false}
#marking and clearing set to true for norway_poles_demo purposes
