local_costmap:
  update_frequency: 2.0 #default: 5.0
  publish_frequency: 2.0 #default: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.04

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
    #- {name: agri_costmap_layer, type: "custom_layer::AgriCostmapLayer_v2"}
